// Generated by gencpp from file create_node/SetTurtlebotModeRequest.msg
// DO NOT EDIT!


#ifndef CREATE_NODE_MESSAGE_SETTURTLEBOTMODEREQUEST_H
#define CREATE_NODE_MESSAGE_SETTURTLEBOTMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_node
{
template <class ContainerAllocator>
struct SetTurtlebotModeRequest_
{
  typedef SetTurtlebotModeRequest_<ContainerAllocator> Type;

  SetTurtlebotModeRequest_()
    : mode(0)  {
    }
  SetTurtlebotModeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTurtlebotModeRequest_

typedef ::create_node::SetTurtlebotModeRequest_<std::allocator<void> > SetTurtlebotModeRequest;

typedef boost::shared_ptr< ::create_node::SetTurtlebotModeRequest > SetTurtlebotModeRequestPtr;
typedef boost::shared_ptr< ::create_node::SetTurtlebotModeRequest const> SetTurtlebotModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator1> & lhs, const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator1> & lhs, const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace create_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_node/SetTurtlebotModeRequest";
  }

  static const char* value(const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
;
  }

  static const char* value(const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTurtlebotModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_node::SetTurtlebotModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create_node::SetTurtlebotModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_NODE_MESSAGE_SETTURTLEBOTMODEREQUEST_H
