(cl:defpackage olfaction_msgs-srv
  (:use )
  (:export
   "SUGGESTNEXTOBSERVATIONLOCATION"
   "<SUGGESTNEXTOBSERVATIONLOCATION-REQUEST>"
   "SUGGESTNEXTOBSERVATIONLOCATION-REQUEST"
   "<SUGGESTNEXTOBSERVATIONLOCATION-RESPONSE>"
   "SUGGESTNEXTOBSERVATIONLOCATION-RESPONSE"
  ))

