(cl:defpackage gaden_player-srv
  (:use )
  (:export
   "GASPOSITION"
   "<GASPOSITION-REQUEST>"
   "GASPOSITION-REQUEST"
   "<GASPOSITION-RESPONSE>"
   "GASPOSITION-RESPONSE"
   "WINDPOSITION"
   "<WINDPOSITION-REQUEST>"
   "WINDPOSITION-REQUEST"
   "<WINDPOSITION-RESPONSE>"
   "WINDPOSITION-RESPONSE"
  ))

