// Generated by gencpp from file gaden_player/GasPosition.msg
// DO NOT EDIT!


#ifndef GADEN_PLAYER_MESSAGE_GASPOSITION_H
#define GADEN_PLAYER_MESSAGE_GASPOSITION_H

#include <ros/service_traits.h>


#include <gaden_player/GasPositionRequest.h>
#include <gaden_player/GasPositionResponse.h>


namespace gaden_player
{

struct GasPosition
{

typedef GasPositionRequest Request;
typedef GasPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GasPosition
} // namespace gaden_player


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaden_player::GasPosition > {
  static const char* value()
  {
    return "a31b6d25f795275d0b32473395891f52";
  }

  static const char* value(const ::gaden_player::GasPosition&) { return value(); }
};

template<>
struct DataType< ::gaden_player::GasPosition > {
  static const char* value()
  {
    return "gaden_player/GasPosition";
  }

  static const char* value(const ::gaden_player::GasPosition&) { return value(); }
};


// service_traits::MD5Sum< ::gaden_player::GasPositionRequest> should match
// service_traits::MD5Sum< ::gaden_player::GasPosition >
template<>
struct MD5Sum< ::gaden_player::GasPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaden_player::GasPosition >::value();
  }
  static const char* value(const ::gaden_player::GasPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaden_player::GasPositionRequest> should match
// service_traits::DataType< ::gaden_player::GasPosition >
template<>
struct DataType< ::gaden_player::GasPositionRequest>
{
  static const char* value()
  {
    return DataType< ::gaden_player::GasPosition >::value();
  }
  static const char* value(const ::gaden_player::GasPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaden_player::GasPositionResponse> should match
// service_traits::MD5Sum< ::gaden_player::GasPosition >
template<>
struct MD5Sum< ::gaden_player::GasPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaden_player::GasPosition >::value();
  }
  static const char* value(const ::gaden_player::GasPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaden_player::GasPositionResponse> should match
// service_traits::DataType< ::gaden_player::GasPosition >
template<>
struct DataType< ::gaden_player::GasPositionResponse>
{
  static const char* value()
  {
    return DataType< ::gaden_player::GasPosition >::value();
  }
  static const char* value(const ::gaden_player::GasPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GADEN_PLAYER_MESSAGE_GASPOSITION_H
