// Generated by gencpp from file olfaction_msgs/suggestNextObservationLocationRequest.msg
// DO NOT EDIT!


#ifndef OLFACTION_MSGS_MESSAGE_SUGGESTNEXTOBSERVATIONLOCATIONREQUEST_H
#define OLFACTION_MSGS_MESSAGE_SUGGESTNEXTOBSERVATIONLOCATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace olfaction_msgs
{
template <class ContainerAllocator>
struct suggestNextObservationLocationRequest_
{
  typedef suggestNextObservationLocationRequest_<ContainerAllocator> Type;

  suggestNextObservationLocationRequest_()
    {
    }
  suggestNextObservationLocationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct suggestNextObservationLocationRequest_

typedef ::olfaction_msgs::suggestNextObservationLocationRequest_<std::allocator<void> > suggestNextObservationLocationRequest;

typedef boost::shared_ptr< ::olfaction_msgs::suggestNextObservationLocationRequest > suggestNextObservationLocationRequestPtr;
typedef boost::shared_ptr< ::olfaction_msgs::suggestNextObservationLocationRequest const> suggestNextObservationLocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace olfaction_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "olfaction_msgs/suggestNextObservationLocationRequest";
  }

  static const char* value(const ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct suggestNextObservationLocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::olfaction_msgs::suggestNextObservationLocationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OLFACTION_MSGS_MESSAGE_SUGGESTNEXTOBSERVATIONLOCATIONREQUEST_H
