// Generated by gencpp from file gaden_player/GasPositionRequest.msg
// DO NOT EDIT!


#ifndef GADEN_PLAYER_MESSAGE_GASPOSITIONREQUEST_H
#define GADEN_PLAYER_MESSAGE_GASPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gaden_player
{
template <class ContainerAllocator>
struct GasPositionRequest_
{
  typedef GasPositionRequest_<ContainerAllocator> Type;

  GasPositionRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  GasPositionRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::gaden_player::GasPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gaden_player::GasPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GasPositionRequest_

typedef ::gaden_player::GasPositionRequest_<std::allocator<void> > GasPositionRequest;

typedef boost::shared_ptr< ::gaden_player::GasPositionRequest > GasPositionRequestPtr;
typedef boost::shared_ptr< ::gaden_player::GasPositionRequest const> GasPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gaden_player::GasPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gaden_player::GasPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gaden_player::GasPositionRequest_<ContainerAllocator1> & lhs, const ::gaden_player::GasPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gaden_player::GasPositionRequest_<ContainerAllocator1> & lhs, const ::gaden_player::GasPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gaden_player

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gaden_player::GasPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaden_player::GasPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaden_player::GasPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::gaden_player::GasPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gaden_player/GasPositionRequest";
  }

  static const char* value(const ::gaden_player::GasPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gaden_player::GasPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GasPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gaden_player::GasPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gaden_player::GasPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GADEN_PLAYER_MESSAGE_GASPOSITIONREQUEST_H
