// Generated by gencpp from file gaden_player/WindPositionResponse.msg
// DO NOT EDIT!


#ifndef GADEN_PLAYER_MESSAGE_WINDPOSITIONRESPONSE_H
#define GADEN_PLAYER_MESSAGE_WINDPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gaden_player
{
template <class ContainerAllocator>
struct WindPositionResponse_
{
  typedef WindPositionResponse_<ContainerAllocator> Type;

  WindPositionResponse_()
    : u(0.0)
    , v(0.0)
    , w(0.0)  {
    }
  WindPositionResponse_(const ContainerAllocator& _alloc)
    : u(0.0)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _u_type;
  _u_type u;

   typedef double _v_type;
  _v_type v;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::gaden_player::WindPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gaden_player::WindPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WindPositionResponse_

typedef ::gaden_player::WindPositionResponse_<std::allocator<void> > WindPositionResponse;

typedef boost::shared_ptr< ::gaden_player::WindPositionResponse > WindPositionResponsePtr;
typedef boost::shared_ptr< ::gaden_player::WindPositionResponse const> WindPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gaden_player::WindPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gaden_player::WindPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gaden_player::WindPositionResponse_<ContainerAllocator1> & lhs, const ::gaden_player::WindPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gaden_player::WindPositionResponse_<ContainerAllocator1> & lhs, const ::gaden_player::WindPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gaden_player

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gaden_player::WindPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaden_player::WindPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaden_player::WindPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a7cd547041f50f35eb6c6911b19ba42";
  }

  static const char* value(const ::gaden_player::WindPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a7cd547041f50f3ULL;
  static const uint64_t static_value2 = 0x5eb6c6911b19ba42ULL;
};

template<class ContainerAllocator>
struct DataType< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gaden_player/WindPositionResponse";
  }

  static const char* value(const ::gaden_player::WindPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 u\n"
"float64 v\n"
"float64 w\n"
"\n"
;
  }

  static const char* value(const ::gaden_player::WindPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WindPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gaden_player::WindPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gaden_player::WindPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GADEN_PLAYER_MESSAGE_WINDPOSITIONRESPONSE_H
