// Generated by gencpp from file gaden_player/WindPosition.msg
// DO NOT EDIT!


#ifndef GADEN_PLAYER_MESSAGE_WINDPOSITION_H
#define GADEN_PLAYER_MESSAGE_WINDPOSITION_H

#include <ros/service_traits.h>


#include <gaden_player/WindPositionRequest.h>
#include <gaden_player/WindPositionResponse.h>


namespace gaden_player
{

struct WindPosition
{

typedef WindPositionRequest Request;
typedef WindPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WindPosition
} // namespace gaden_player


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaden_player::WindPosition > {
  static const char* value()
  {
    return "c7d239bda793d989e4c3fa81d8d2b731";
  }

  static const char* value(const ::gaden_player::WindPosition&) { return value(); }
};

template<>
struct DataType< ::gaden_player::WindPosition > {
  static const char* value()
  {
    return "gaden_player/WindPosition";
  }

  static const char* value(const ::gaden_player::WindPosition&) { return value(); }
};


// service_traits::MD5Sum< ::gaden_player::WindPositionRequest> should match
// service_traits::MD5Sum< ::gaden_player::WindPosition >
template<>
struct MD5Sum< ::gaden_player::WindPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaden_player::WindPosition >::value();
  }
  static const char* value(const ::gaden_player::WindPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaden_player::WindPositionRequest> should match
// service_traits::DataType< ::gaden_player::WindPosition >
template<>
struct DataType< ::gaden_player::WindPositionRequest>
{
  static const char* value()
  {
    return DataType< ::gaden_player::WindPosition >::value();
  }
  static const char* value(const ::gaden_player::WindPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaden_player::WindPositionResponse> should match
// service_traits::MD5Sum< ::gaden_player::WindPosition >
template<>
struct MD5Sum< ::gaden_player::WindPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaden_player::WindPosition >::value();
  }
  static const char* value(const ::gaden_player::WindPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaden_player::WindPositionResponse> should match
// service_traits::DataType< ::gaden_player::WindPosition >
template<>
struct DataType< ::gaden_player::WindPositionResponse>
{
  static const char* value()
  {
    return DataType< ::gaden_player::WindPosition >::value();
  }
  static const char* value(const ::gaden_player::WindPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GADEN_PLAYER_MESSAGE_WINDPOSITION_H
