# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from olfaction_msgs/gas_sensor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class gas_sensor(genpy.Message):
  _md5sum = "f19a4378539410bc0da063e4424de564"
  _type = "olfaction_msgs/gas_sensor"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Generic gas sensor msg

# TECHNOLOGY -------------------------------------------------------------------
uint8 TECH_UNKNOWN   = 0
uint8 TECH_MOX       = 1
uint8 TECH_AEC       = 2
uint8 TECH_EQ        = 50
uint8 TECH_PID       = 51
uint8 TECH_SAW       = 52
uint8 TECH_TEMP      = 100
uint8 TECH_HUMIDITY  = 101
uint8 TECH_NOT_VALID = 255


# MANUFACTURER -----------------------------------------------------------------
uint8 MANU_UNKNOWN   = 0
uint8 MANU_FIGARO    = 1
uint8 MANU_ALPHASENSE= 2
uint8 MANU_SGX       = 3
uint8 MANU_RAE       = 50
uint8 MANU_HANWEI    = 51
uint8 MANU_NOT_VALID = 255



# MPN --------------------------------------------------------------------------
uint8 MPN_UNKNOWN    = 0
uint8 MPN_TGS2620    = 50
uint8 MPN_TGS2600    = 51
uint8 MPN_TGS2611    = 52
uint8 MPN_TGS2610    = 53
uint8 MPN_TGS2612    = 54
uint8 MPN_MINIRAELITE= 70
uint8 MPN_NOT_VALID  = 255



# UNITS ------------------------------------------------------------------------
uint8 UNITS_UNKNOWN          = 0
uint8 UNITS_VOLT             = 1
uint8 UNITS_AMP              = 2
uint8 UNITS_PPM              = 3
uint8 UNITS_PPB              = 4
uint8 UNITS_OHM              = 5
uint8 UNITS_CENTIGRADE       = 100
uint8 UNITS_RELATIVEHUMIDITY = 101
uint8 UNITS_NOT_VALID        = 255



# MESSAGE DEFINITION -----------------------------------------------------------

Header header       # timestamp and frame_id

#Info
uint8 technology
uint8 manufacturer
uint8 mpn

#Measurement
float64 raw
uint8 raw_units     # Measurement units (e.g. ppm, volts, ohm)
float64 raw_air     # Sensor output for clean air
float64 calib_A     # Calibration constant. Its exact meaning depends on the sensor
float64 calib_B     # Calibration constant. Its exact meaning depends on the sensor


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  TECH_UNKNOWN = 0
  TECH_MOX = 1
  TECH_AEC = 2
  TECH_EQ = 50
  TECH_PID = 51
  TECH_SAW = 52
  TECH_TEMP = 100
  TECH_HUMIDITY = 101
  TECH_NOT_VALID = 255
  MANU_UNKNOWN = 0
  MANU_FIGARO = 1
  MANU_ALPHASENSE = 2
  MANU_SGX = 3
  MANU_RAE = 50
  MANU_HANWEI = 51
  MANU_NOT_VALID = 255
  MPN_UNKNOWN = 0
  MPN_TGS2620 = 50
  MPN_TGS2600 = 51
  MPN_TGS2611 = 52
  MPN_TGS2610 = 53
  MPN_TGS2612 = 54
  MPN_MINIRAELITE = 70
  MPN_NOT_VALID = 255
  UNITS_UNKNOWN = 0
  UNITS_VOLT = 1
  UNITS_AMP = 2
  UNITS_PPM = 3
  UNITS_PPB = 4
  UNITS_OHM = 5
  UNITS_CENTIGRADE = 100
  UNITS_RELATIVEHUMIDITY = 101
  UNITS_NOT_VALID = 255

  __slots__ = ['header','technology','manufacturer','mpn','raw','raw_units','raw_air','calib_A','calib_B']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','float64','uint8','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,technology,manufacturer,mpn,raw,raw_units,raw_air,calib_A,calib_B

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gas_sensor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.technology is None:
        self.technology = 0
      if self.manufacturer is None:
        self.manufacturer = 0
      if self.mpn is None:
        self.mpn = 0
      if self.raw is None:
        self.raw = 0.
      if self.raw_units is None:
        self.raw_units = 0
      if self.raw_air is None:
        self.raw_air = 0.
      if self.calib_A is None:
        self.calib_A = 0.
      if self.calib_B is None:
        self.calib_B = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.technology = 0
      self.manufacturer = 0
      self.mpn = 0
      self.raw = 0.
      self.raw_units = 0
      self.raw_air = 0.
      self.calib_A = 0.
      self.calib_B = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3BdB3d().pack(_x.technology, _x.manufacturer, _x.mpn, _x.raw, _x.raw_units, _x.raw_air, _x.calib_A, _x.calib_B))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.technology, _x.manufacturer, _x.mpn, _x.raw, _x.raw_units, _x.raw_air, _x.calib_A, _x.calib_B,) = _get_struct_3BdB3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3BdB3d().pack(_x.technology, _x.manufacturer, _x.mpn, _x.raw, _x.raw_units, _x.raw_air, _x.calib_A, _x.calib_B))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.technology, _x.manufacturer, _x.mpn, _x.raw, _x.raw_units, _x.raw_air, _x.calib_A, _x.calib_B,) = _get_struct_3BdB3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3BdB3d = None
def _get_struct_3BdB3d():
    global _struct_3BdB3d
    if _struct_3BdB3d is None:
        _struct_3BdB3d = struct.Struct("<3BdB3d")
    return _struct_3BdB3d
