// Generated by gencpp from file olfaction_msgs/anemometer.msg
// DO NOT EDIT!


#ifndef OLFACTION_MSGS_MESSAGE_ANEMOMETER_H
#define OLFACTION_MSGS_MESSAGE_ANEMOMETER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace olfaction_msgs
{
template <class ContainerAllocator>
struct anemometer_
{
  typedef anemometer_<ContainerAllocator> Type;

  anemometer_()
    : header()
    , sensor_label()
    , wind_speed(0.0)
    , wind_direction(0.0)  {
    }
  anemometer_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_label(_alloc)
    , wind_speed(0.0)
    , wind_direction(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_label_type;
  _sensor_label_type sensor_label;

   typedef float _wind_speed_type;
  _wind_speed_type wind_speed;

   typedef float _wind_direction_type;
  _wind_direction_type wind_direction;





  typedef boost::shared_ptr< ::olfaction_msgs::anemometer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::olfaction_msgs::anemometer_<ContainerAllocator> const> ConstPtr;

}; // struct anemometer_

typedef ::olfaction_msgs::anemometer_<std::allocator<void> > anemometer;

typedef boost::shared_ptr< ::olfaction_msgs::anemometer > anemometerPtr;
typedef boost::shared_ptr< ::olfaction_msgs::anemometer const> anemometerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::olfaction_msgs::anemometer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::olfaction_msgs::anemometer_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace olfaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/melodic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'olfaction_msgs': ['/home/bart/CFD_pipeline/catkin_ws/src/olfaction_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::olfaction_msgs::anemometer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::olfaction_msgs::anemometer_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::olfaction_msgs::anemometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::olfaction_msgs::anemometer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::olfaction_msgs::anemometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::olfaction_msgs::anemometer_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::olfaction_msgs::anemometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6eda3f54da66470bd27452be26d76e3";
  }

  static const char* value(const ::olfaction_msgs::anemometer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6eda3f54da66470ULL;
  static const uint64_t static_value2 = 0xbd27452be26d76e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::olfaction_msgs::anemometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "olfaction_msgs/anemometer";
  }

  static const char* value(const ::olfaction_msgs::anemometer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::olfaction_msgs::anemometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header		    #timestamp, frame_id\n"
"\n"
"string sensor_label	    #identifier\n"
"float32 wind_speed	    #m/s\n"
"float32 wind_direction	#rad\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::olfaction_msgs::anemometer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::olfaction_msgs::anemometer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_label);
      stream.next(m.wind_speed);
      stream.next(m.wind_direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct anemometer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::olfaction_msgs::anemometer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::olfaction_msgs::anemometer_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor_label);
    s << indent << "wind_speed: ";
    Printer<float>::stream(s, indent + "  ", v.wind_speed);
    s << indent << "wind_direction: ";
    Printer<float>::stream(s, indent + "  ", v.wind_direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OLFACTION_MSGS_MESSAGE_ANEMOMETER_H
